FROM impfs_base_docker_image

RUN echo edit to rebuild...

# -n means don't build etc
RUN eval `opam config env` && opam pin add -y -n https://github.com/tomjridge/tjr_simple_earley.git
RUN eval `opam config env` && opam install -y tjr_simple_earley
