* Simple Earley Parsing
Author: Tom Ridge

An implementation of an Earley-like algorithm, designed for
simplicity.

** Meta

On github, to preview the documented code, try http://tomjridge.github.io/simple_earley/tjr_earley.html



** Building

To build, type ~make~


** Opam

This is not really intended to be installed as a library. However, in
order to advertise the existence of this code, there needs to be an
entry in the opam packages list. So this package does exist in Opam,
but nothing is installed - the code just gets built.

To see the results of the build, invoke e.g.:

----
opam install -vvv --keep-build-dir tjr_earley 
----

Then you should be able to locate the executables ~test.native~ and
~simple_test.native~



** Running

There are two executables, ~test.native~ and ~simple_test.native~. To
run the Earley parser with the grammar ~E -> E E E | "1" | esp~, with
an input length of 400 say, in the src directory type:

----
test.native 400
----

The output should look like:

----
$ src $ time ./test.native 400
Right hand side suffix count: 8
400

real	0m2.491s
user	0m2.484s
sys	0m0.004s
----

