

# NOTE this file is GENERATED by config.ml_

set -a # export all vars

libname="tjr_simple_earley"
package_name="tjr_simple_earley"

ocamlc="ocamlfind ocamlc -g   "
ocamlopt="ocamlfind ocamlopt -g   "

mls="earley_util.ml tjr_earley.ml fast_datastructure_implementations.ml simple_datastructure_implementations.ml"
cmos="earley_util.cmo tjr_earley.cmo fast_datastructure_implementations.cmo simple_datastructure_implementations.cmo"
cmxs="earley_util.cmx tjr_earley.cmx fast_datastructure_implementations.cmx simple_datastructure_implementations.cmx"

mk_cma="ocamlfind ocamlc -g   "
mk_cmxa="ocamlfind ocamlopt -g   "

