

# NOTE this file is GENERATED by config.ml_

set -a # export all vars

libname="tjr_simple_earley"
package_name="tjr_simple_earley"

ocamlc="ocamlfind ocamlc -g   "
ocamlopt="ocamlfind ocamlopt -g   "

mls="profile_waypoints.ml earley_util.ml tjr_earley.ml"
cmos="profile_waypoints.cmo earley_util.cmo tjr_earley.cmo"
cmxs="profile_waypoints.cmx earley_util.cmx tjr_earley.cmx"

mk_cma="ocamlfind ocamlc -g   "
mk_cmxa="ocamlfind ocamlopt -g   "

