= Staged version of Earley
Author: Tom Ridge
:toc:
:sectnums:
:stem: latexmath
:source-highlighter: pygments


== Comment on datastructures required

The `S_` functor has:

----
  type nt_item = {
    nt: nt;
    i: i_t;
    as_: sym list;  (* NOTE in "reversed" order *)
    k: k_t;
    bs: sym list
  }
----

which could be 3 ints and 2 int lists. The int lists have max length
the max length of any rhs, which is expected to be small. So roughly
this is a list of int, of approx size `2*|rhs| + 3`.


The `Make` functor has type `state_t`:

----
  type state_t = {
    k: int;
    todo: nt_item list;  
    (* per k *)

    todo_done: nt_item_set; 
    (* per k; todo_done at stage k *)

    todo_gt_k: nt_item_set map_int; 
    (* array (int/j) to nt_item_set? empty for large k' > k_current
       and not needed for j<k *)

    ixk_done: ixk_set;  (* i X k *)  
    (* per k; array (int/i) with values a set of nt?; set of nt
       implemented by binary upto 63/64 bits *)

    ktjs: int list option map_tm;  (* k T j *)  
    (* per k; array (tm) with values a list of int *)

    bitms_lt_k: bitms_lt_k;  (* for all k; defined locally, see above *)

    bitms_at_k: bitms_at_k;  (* per k; ditto *)

    all_done: nt_item_set list;  
    (* not really needed - just for returning results as a list *)
  }
----

Maps from int are typically indexed by `k`. Typically eg `todo_gt_k`
would be sparse and, after the first few k, have no entries (since
this gets filled when a terminal completes).

The main datastructure is a "set of nt items". One thing to note is
that, for finite BNFs, there are a very small number of possible `as_`
and `bs`, and that `as_` is determined by `bs`. The operation we have
on `bs` is to take the head, and the tail, and these can be
precomputed based on the grammar.

So an `nt_item` could be `nt*i_t*k_t*(bs)^` where `(bs)^` is the int
repr. of `bs`. This is two small ints and two `length(input)` ints,
one of which can typically be omitted (because known in some other
way.. this is (always?) `k`). So we have `nt * i_t * (bs)^` which is 3
ints (only one of which is expected to be large). 32 bits is enough to
handle inputs of length 2^32 or approx 1GB. Then could use the
remaining 32 (31) bits to record nt and `(bs)^`. This would give an
efficient implementation of `nt_item_set` which is not scanned by the
GC.

Of interest is that OCaml GC does not scan float arrays (but does scan
int arrays), see
https://stackoverflow.com/questions/42976380/ocaml-int-array-and-garbage-collection . 

That post suggests that bigarrays can be used when gc is an issue.


== `step_k`

This version processes all items at index latexmath:[k] (the current
stage) before moving on to latexmath:[k+1] (the next stage).


`nitm.complete`, true::
We have a complete item `(i,X,k)`.

`already_done`, true:::

If the item has already been processed, don't do anything.

`already_done`, false:::

Otherwise, add to `ixk_done` map.
Then we need to process the complete item against the blocked items.

`nitm.complete`, false::

Otherwise, we have an item `(X -> i as k (S bs'))` blocked on `k,S`.

`S` is a nonterminal `_Y`:::

Then record the new blocked item.

`bitms_empty`, false::::

If we have already processed `k,Y` (ie, this is not the first time we
have seen nonterminal `Y` at stage `k`) then we don't need to expand
`Y`, but we may have to consider the interaction of `bitm` with the
complete item `(k,Y,k)`: if the complete item has been found, we need
to cut it against the blocked item.

`bitms_empty`, true::::

If we haven't processed nt `Y` yet expand `Y`, and add new items. Note
that there cannot be any complete items `(k,Y,k)` because this is the
first time we are processing `Y` at this stage.

`S` is a terminal `T`:::

We need to bind `js` to the indexes
resulting from a terminal parse of `T` at this stage. 
//-
If we have not
already dealt with `T` at the current stage we use the terminal parser
to get a list of indexes `j`, and update the `ktjs` map.
//-
If we have already dealt with `T` at the current stage we use the
results of the initial parse of `T`.
//-
Now we have `js`, corresponding to a set of complete items. We need to
process these against the relevant blocked items. Note that we only
parse a terminal once at stage `k`, and this occurs when we meet the
first corresponding blocked item. Thus, there is only one blocked item
at this point.

// If we have expanded T previously, why do we need to process it against
// blocked items at this point? Because every time we have a new blocked
// item, we have to process it against all complete items.


== Loop at k


== Earley loop over all k


Initialize state, and run Earley loop.
